// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Configurator.API.Migrations
{
    [DbContext(typeof(ConfiguratorDbContext))]
    [Migration("20250518035509_SamboGearTable")]
    partial class SamboGearTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("configurator")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Common.DomainObjects.GearSpec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("createdbyid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("createddate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("ModifiedById")
                        .HasColumnType("integer")
                        .HasColumnName("modifiedbyid");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("modifieddate");

                    b.Property<string>("SpecCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("speccode");

                    b.HasKey("Id")
                        .HasName("pk_gearspecs");

                    b.ToTable("gearspecs", "configurator");
                });

            modelBuilder.Entity("SamboGear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("createdbyid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("createddate");

                    b.Property<decimal?>("EfficiencyRun")
                        .HasColumnType("numeric")
                        .HasColumnName("efficiencyrun");

                    b.Property<decimal?>("EfficiencyStall")
                        .HasColumnType("numeric")
                        .HasColumnName("efficiencystall");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("family");

                    b.Property<int?>("HandwheelDiameterMm")
                        .HasColumnType("integer")
                        .HasColumnName("handwheeldiametermm");

                    b.Property<string>("KeySize")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("keysize");

                    b.Property<int?>("MaxThrustN")
                        .HasColumnType("integer")
                        .HasColumnName("maxthrustn");

                    b.Property<string>("ModelCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("modelcode");

                    b.Property<int>("ModifiedById")
                        .HasColumnType("integer")
                        .HasColumnName("modifiedbyid");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("modifieddate");

                    b.Property<string>("MountingIso")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mountingiso");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<int?>("OutputTorqueNm")
                        .HasColumnType("integer")
                        .HasColumnName("outputtorquenm");

                    b.Property<string>("SizeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("sizecode");

                    b.Property<decimal?>("StemBoreInches")
                        .HasColumnType("numeric")
                        .HasColumnName("stemboreinches");

                    b.Property<decimal?>("StemBoreMm")
                        .HasColumnType("numeric")
                        .HasColumnName("stemboremm");

                    b.Property<int?>("TurnsToOpen")
                        .HasColumnType("integer")
                        .HasColumnName("turnstoopen");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("numeric")
                        .HasColumnName("weightkg");

                    b.HasKey("Id")
                        .HasName("pk_sambogears");

                    b.ToTable("sambogears", "configurator");
                });

            modelBuilder.Entity("SamboGearMountingBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("createdbyid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("createddate");

                    b.Property<int>("ModifiedById")
                        .HasColumnType("integer")
                        .HasColumnName("modifiedbyid");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("modifieddate");

                    b.Property<string>("MountingBaseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mountingbasecode");

                    b.Property<int>("SamboGearId")
                        .HasColumnType("integer")
                        .HasColumnName("sambogearid");

                    b.HasKey("Id")
                        .HasName("pk_sambogearmountingbases");

                    b.HasIndex("SamboGearId")
                        .HasDatabaseName("ix_sambogearmountingbases_sambogearid");

                    b.ToTable("sambogearmountingbases", "configurator");
                });

            modelBuilder.Entity("WormGearOperator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("createdbyid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("createddate");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("family");

                    b.Property<bool>("HandwheelIncluded")
                        .HasColumnType("boolean")
                        .HasColumnName("handwheelincluded");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("material");

                    b.Property<int>("ModifiedById")
                        .HasColumnType("integer")
                        .HasColumnName("modifiedbyid");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("modifieddate");

                    b.Property<string>("MountingStandard")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mountingstandard");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("operationtype");

                    b.Property<string>("PartNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("partnumber");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("size");

                    b.Property<int>("TorqueRatingNm")
                        .HasColumnType("integer")
                        .HasColumnName("torqueratingnm");

                    b.Property<bool>("Weatherproof")
                        .HasColumnType("boolean")
                        .HasColumnName("weatherproof");

                    b.HasKey("Id")
                        .HasName("pk_wormgearoperators");

                    b.ToTable("wormgearoperators", "configurator");
                });

            modelBuilder.Entity("SamboGearMountingBase", b =>
                {
                    b.HasOne("SamboGear", "SamboGear")
                        .WithMany("MountingBases")
                        .HasForeignKey("SamboGearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sambogearmountingbases_sambogears_sambogearid");

                    b.Navigation("SamboGear");
                });

            modelBuilder.Entity("SamboGear", b =>
                {
                    b.Navigation("MountingBases");
                });
#pragma warning restore 612, 618
        }
    }
}
