// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Configurator.API.Migrations
{
    [DbContext(typeof(ConfiguratorDbContext))]
    [Migration("20250517140836_InitialConfiguratorDb")]
    partial class InitialConfiguratorDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("configurator")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Common.DomainObjects.GearSpec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CreatedById")
                        .HasColumnType("integer")
                        .HasColumnName("createdbyid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("createddate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("ModifiedById")
                        .HasColumnType("integer")
                        .HasColumnName("modifiedbyid");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("timestamp")
                        .HasColumnName("modifieddate");

                    b.Property<string>("SpecCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("speccode");

                    b.HasKey("Id")
                        .HasName("pk_gearspecs");

                    b.ToTable("gearspecs", "configurator");
                });
#pragma warning restore 612, 618
        }
    }
}
